11.0: Pulling from library/odoo
Attaching to docker-odoo-110_db_1, docker-odoo-110_web_1
[36mdb_1   |[0m The files belonging to this database system will be owned by user "postgres".
[36mdb_1   |[0m This user must also own the server process.
[36mdb_1   |[0m 
[36mdb_1   |[0m The database cluster will be initialized with locale "en_US.utf8".
[36mdb_1   |[0m The default database encoding has accordingly been set to "UTF8".
[36mdb_1   |[0m The default text search configuration will be set to "english".
[36mdb_1   |[0m 
[36mdb_1   |[0m Data page checksums are disabled.
[36mdb_1   |[0m 
[36mdb_1   |[0m fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
[36mdb_1   |[0m creating subdirectories ... ok
[36mdb_1   |[0m selecting default max_connections ... 100
[36mdb_1   |[0m selecting default shared_buffers ... 128MB
[36mdb_1   |[0m selecting dynamic shared memory implementation ... posix
[36mdb_1   |[0m creating configuration files ... ok
[36mdb_1   |[0m running bootstrap script ... ok
[36mdb_1   |[0m performing post-bootstrap initialization ... ok
[36mdb_1   |[0m syncing data to disk ... 
[36mdb_1   |[0m WARNING: enabling "trust" authentication for local connections
[36mdb_1   |[0m You can change this by editing pg_hba.conf or using the option -A, or
[36mdb_1   |[0m --auth-local and --auth-host, the next time you run initdb.
[36mdb_1   |[0m ok
[36mdb_1   |[0m 
[36mdb_1   |[0m Success. You can now start the database server using:
[36mdb_1   |[0m 
[36mdb_1   |[0m     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
[36mdb_1   |[0m 
[36mdb_1   |[0m waiting for server to start....2019-01-19 17:59:02.815 UTC [38] LOG:  listening on IPv4 address "127.0.0.1", port 5432
[36mdb_1   |[0m 2019-01-19 17:59:02.815 UTC [38] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
[36mdb_1   |[0m 2019-01-19 17:59:02.815 UTC [38] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
[36mdb_1   |[0m 2019-01-19 17:59:03.697 UTC [38] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m .2019-01-19 17:59:03.926 UTC [39] LOG:  database system was shut down at 2019-01-19 17:59:00 UTC
[36mdb_1   |[0m 2019-01-19 17:59:04.046 UTC [38] LOG:  database system is ready to accept connections
[36mdb_1   |[0m  done
[36mdb_1   |[0m server started
[36mdb_1   |[0m CREATE DATABASE
[36mdb_1   |[0m 
[33mweb_1  |[0m ERROR: couldn't create the logfile directory. Logging to the standard output.
[33mweb_1  |[0m 2019-01-19 17:59:05,735 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
[33mweb_1  |[0m 2019-01-19 17:59:05,736 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
[33mweb_1  |[0m 2019-01-19 17:59:05,736 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
[33mweb_1  |[0m 2019-01-19 17:59:05,737 1 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
[33mweb_1  |[0m 2019-01-19 17:59:05,737 1 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
[33mweb_1  |[0m 2019-01-19 17:59:05,737 1 DEBUG ? odoo.netsvc: logger level set: "[':DEBUG']"
[33mweb_1  |[0m 2019-01-19 17:59:05,738 1 INFO ? odoo: Odoo version 11.0-20181126
[33mweb_1  |[0m 2019-01-19 17:59:05,738 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
[33mweb_1  |[0m 2019-01-19 17:59:05,738 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
[33mweb_1  |[0m 2019-01-19 17:59:05,739 1 INFO ? odoo: database: odoo@db:5432
[33mweb_1  |[0m 2019-01-19 17:59:05,766 1 DEBUG ? odoo.service.server: Setting signal handlers
[33mweb_1  |[0m 2019-01-19 17:59:05,771 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on f1348988a3c2:8069
[33mweb_1  |[0m 2019-01-19 17:59:05,771 1 DEBUG ? odoo.service.server: cron0 started!
[33mweb_1  |[0m 2019-01-19 17:59:05,772 1 DEBUG ? odoo.service.server: cron1 started!
[36mdb_1   |[0m CREATE ROLE
[36mdb_1   |[0m 
[36mdb_1   |[0m 
[36mdb_1   |[0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
[36mdb_1   |[0m 
[36mdb_1   |[0m 2019-01-19 17:59:05.809 UTC [38] LOG:  received fast shutdown request
[33mweb_1  |[0m 2019-01-19 17:59:05,982 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
[36mdb_1   |[0m waiting for server to shut down....2019-01-19 17:59:06.058 UTC [38] LOG:  aborting any active transactions
[36mdb_1   |[0m 2019-01-19 17:59:06.063 UTC [38] LOG:  worker process: logical replication launcher (PID 45) exited with exit code 1
[36mdb_1   |[0m 2019-01-19 17:59:06.063 UTC [40] LOG:  shutting down
[33mweb_1  |[0m 2019-01-19 17:59:06,171 1 DEBUG ? odoo.tools.translate: translation went wrong for "'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.'", skipped
[36mdb_1   |[0m 2019-01-19 17:59:06.463 UTC [38] LOG:  database system is shut down
[36mdb_1   |[0m  done
[36mdb_1   |[0m server stopped
[36mdb_1   |[0m 
[36mdb_1   |[0m PostgreSQL init process complete; ready for start up.
[36mdb_1   |[0m 
[36mdb_1   |[0m 2019-01-19 17:59:06.619 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[36mdb_1   |[0m 2019-01-19 17:59:06.619 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[36mdb_1   |[0m 2019-01-19 17:59:06.785 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2019-01-19 17:59:07.063 UTC [65] LOG:  database system was shut down at 2019-01-19 17:59:06 UTC
[36mdb_1   |[0m 2019-01-19 17:59:07.153 UTC [1] LOG:  database system is ready to accept connections
[33mweb_1  |[0m 2019-01-19 18:00:06,297 1 DEBUG ? odoo.service.server: cron0 polling for jobs
[33mweb_1  |[0m 2019-01-19 18:00:07,356 1 DEBUG ? odoo.service.server: cron1 polling for jobs
Gracefully stopping... (press Ctrl+C again to force)
Attaching to docker-odoo-110_db_1, docker-odoo-110_web_1
[36mdb_1   |[0m 2019-01-21 12:33:33.828 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[36mdb_1   |[0m 2019-01-21 12:33:33.828 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[36mdb_1   |[0m 2019-01-21 12:33:34.147 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2019-01-21 12:33:34.521 UTC [23] LOG:  database system was shut down at 2019-01-19 18:01:04 UTC
[36mdb_1   |[0m 2019-01-21 12:33:34.613 UTC [1] LOG:  database system is ready to accept connections
[33mweb_1  |[0m ERROR: couldn't create the logfile directory. Logging to the standard output.
[33mweb_1  |[0m 2019-01-21 12:33:43,572 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
[33mweb_1  |[0m 2019-01-21 12:33:43,572 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 DEBUG ? odoo.netsvc: logger level set: "[':DEBUG']"
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 INFO ? odoo: Odoo version 11.0-20181126
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
[33mweb_1  |[0m 2019-01-21 12:33:43,573 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
[33mweb_1  |[0m 2019-01-21 12:33:43,574 1 INFO ? odoo: database: odoo@db:5432
[33mweb_1  |[0m 2019-01-21 12:33:43,718 1 DEBUG ? odoo.service.server: Setting signal handlers
[33mweb_1  |[0m 2019-01-21 12:33:43,730 1 DEBUG ? odoo.service.server: cron0 started!
[33mweb_1  |[0m 2019-01-21 12:33:43,731 1 DEBUG ? odoo.service.server: cron1 started!
[33mweb_1  |[0m 2019-01-21 12:33:43,736 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on f1348988a3c2:8069
[33mweb_1  |[0m 2019-01-21 12:33:44,682 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
[33mweb_1  |[0m 2019-01-21 12:33:45,864 1 DEBUG ? odoo.tools.translate: translation went wrong for "'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.'", skipped
[33mweb_1  |[0m 2019-01-21 12:34:46,178 1 DEBUG ? odoo.service.server: cron0 polling for jobs
[33mweb_1  |[0m 2019-01-21 12:34:47,197 1 DEBUG ? odoo.service.server: cron1 polling for jobs
